theme: jekyll-theme-cayman

markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: false
  include:
    - CodeStyle.md
    
sass:
  sass_dir: _sass
  style: compressed