theme: jekyll-theme-cayman
markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
plugins:
  - jekyll-relative-links
  - jekyll-last-modified-at
relative_links:
  enabled: true
  collections: true
include:
  - CodeStyle.md