theme: jekyll-theme-cayman

permalink: /:collection/:title/

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - README.md

plugins:
  - jekyll-commonmark-ghpages
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# for jekyll-commonmark-ghpages
# docs for options: https://github.com/gjtorikian/commonmarker#options
# docs for extensions: https://github.com/gjtorikian/commonmarker#extensions
markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter", "tasklist"]

# for jekyll-feed
author: DarkContact

# for jekyll-seo-tag
title: DarkContact Secret Place
tagline: Блог об играх и программировании
description: Блог об играх и программировании
locale: ru_RU

# for jekyll-sitemap
url: "https://darkcontact.github.io"

# for jekyll-paginate
paginate: 5
paginate_path: "/blog/page:num/"

# variables for all pages
# exclude webmaster pages from sitemap.xml
defaults:
  - scope:
      path: ""
    values:
      show_navigation: true
      blog_navigation_active: false
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      blog_navigation_active: true
  - scope:
      path: "webmaster/google29bef1b63874caf4.html"
    values:
      sitemap: false
      layout: null
  - scope:
      path: "webmaster/yandex_35403b5c7aa6b72a.html"
    values:
      sitemap: false
      layout: null
  - scope:
      path: "test"
    values:
      sitemap: false
  - scope:
      path: "blog"
    values:
      blog_navigation_active: true

  # for jekyll-seo-tag (ogp image)
  # - scope:
  #     path: ""
  #   values:
  #     image: /assets/images/default-card.png
 