theme: jekyll-theme-cayman

plugins:
  - jekyll-relative-links
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
 
# for jekyll-sitemap
url: "https://darkcontact.github.io/" 

relative_links:
  enabled: true
  collections: false
  include:
    - CodeStyle.md
    
sass:
  sass_dir: _sass
  style: compressed