theme: jekyll-theme-cayman

permalink: /:title/

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - README.md

plugins:
  - jekyll-commonmark-ghpages
  - jekyll-relative-links
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# for jekyll-commonmark-ghpages
# docs for options: https://github.com/gjtorikian/commonmarker#options
# docs for extensions: https://github.com/gjtorikian/commonmarker#extensions
markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

# for jekyll-relative-links
relative_links:
  enabled: true
  collections: false
  include:
    - CodeStyle.md

# for jekyll-feed
author: DarkContact

# for jekyll-seo-tag
title: DarkContact Secret Place
tagline: Блог об играх и программировании
description: Блог об играх и программировании
locale: ru_RU

# for jekyll-seo-tag (ogp image)
  # - scope:
  #     path: ""
  #   values:
  #     image: /assets/images/default-card.png

# for jekyll-sitemap
url: "https://darkcontact.github.io" 

# exclude webmaster pages from sitemap.xml 
defaults:
  - scope:
      path: "webmaster/google29bef1b63874caf4.html"
    values:
      sitemap: false
      layout: null
  - scope:
      path: "webmaster/yandex_35403b5c7aa6b72a.html"
    values:
      sitemap: false
      layout: null