theme: jekyll-theme-cayman

plugins:
  - jekyll-relative-links
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

relative_links:
  enabled: true
  collections: false
  include:
    - CodeStyle.md
    
sass:
  sass_dir: _sass
  style: compressed

# for jekyll-sitemap
url: "https://darkcontact.github.io" 

# exclude pages from sitemap.xml
defaults:
  - 
    scope:
      path: "google29bef1b63874caf4.html"
    values:
      sitemap: false
  - 
    scope:
      path: "yandex_35403b5c7aa6b72a.html"
    values:
      sitemap: false